### PR TITLE
Allow for changing an tag when clicking on it

### PR DESCRIPTION
**Pull request by sstok**
I have add an new tagClick event which allows for changing the value of an tag by clicking on it.

The event will receive the data as Item and must return it as an Item.
Writing an automated test-case was not possible since I don''t have the software for running them.

The usage is actually self explanatory.

``` JavaScript
// Data is the data as it was added
textarea.bind('tagClick', function (e, Data){
    // Normally you would use something more fancy, like jQuery UI dialog.
    var newLabel = window.prompt('New value', Data);

    if (newLabel)
        Data = newLabel;
});
```

### CODE REVIEW

**Comment by alexgorbatchev** [comment]
Thank you for the patch, I'll check it out shortly!

**Comment by sstok** [comment]
There still some issues, the trigger expects an return. But that is not possible with dialogs that works with callbacks like most of them do.

So there must be a second method that will actually trigger the update.
Now I need to find a way to make a reference to that 'trigger' function possible from inside the callback.
And that where I'm stuck right now... My best shot is registering an internal callback that gets fired from inside the callback of the dialog.

**Comment by sstok** [comment]
The issue has been resolved, any change on seeing this getting merged soon?

**Comment by alexgorbatchev** [comment]
@sstok Thanks for the path and idea. I've reimplemented it slightly to be more consistent with the rest of the code base. Please have a look https://github.com/alexgorbatchev/jquery-textext/commit/22edd913ff107aad3739286c3c75c880617a5d76#L2R131

**Comment by sstok** [comment]
Great! Thanks.

**Pull request merged**
